sirc-e5orlnb7-IAM:
  prefix: sirc-e5orlnb7
  stackName: sirc-e5orlnb7-iams
  system_bucket: {{buckets.internal.name}}
  useNgapPermissionBoundary: true
  buckets:
    internal:
        name: sirc-e5orlnb7-internal
        type: internal
    private:
        name: sirc-e5orlnb7-private
        type: private
    protected: 
        name: sirc-e5orlnb7-protected
        type: protected
    public:
        name: sirc-e5orlnb7-public
        type: public
